# Yawa - general all-in-one plugin for any of my personally deployed minecraft servers.
#
# https://github.com/gavenda/yawa
#
# The main reason this plugin was created so I can instantly get server up to date with any Spigot updates or fix
# any errors I found and also remove unnecessary features I don't really want.
#
# This is simply micro optimizing, and yes, I'm doing it for evil.

# Database configuration
db:
  # You can use any jdbc url as long as you can somehow provide the driver on the classpath
  # By default it is set to use SQLite
  # Use this for MySQL connections: <jdbc:mysql://localhost:3306/db>
  jdbc-url: "jdbc:sqlite:plugins/Yawa/yawa.db"
  username: root
  password: ''

# Permission feature configuration
permission:
  disabled: true

# Essentials feature configuration
essentials:
  disabled: true

# Ping feature configuration
ping:
  disabled: false

# Hidden armor feature configuration
hidden-armor:
  disabled: false

# Player head feature configuration
player-head:
  disabled: false

# Tab List feature configuration
tab-list:
  disabled: false
  header: "<gold>Yawa</gold>"
  footer: "<server-player-count> / <server-player-max>"

# Sleep - Configure how we pass the night, defaults to desired values.
# based on Harbor (https://github.com/nkomarn/Harbor)
sleep:
  disabled: false
  time-rate: 85
  kick-seconds: 15
  messages:
    chat:
      enabled: true

# Ender dragon battle configuration
ender:
  disabled: true

# Sit feature configuration
sit:
  disabled: false

# Skin feature configuration
skin:
  disabled: false
  default-texture:
    value: "eyJ0aW1lc3RhbXAiOjE1ODc5NTIzNzQ4MDcsInByb2ZpbGVJZCI6IjBmNjQ3NDFlNDAzMjQ2ZGY5NDdmZmFiYTg5Yzc5ZGQwIiwicHJvZmlsZU5hbWUiOiJOb29vb29vb29vb29vbzAwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MzkzNDE4MzQ4NTY2NzMyMWM5YWQ1OGM0YWQwMzM3N2IwMjBhOGI3ODEwYzgyZWEzMDQ4YmVlOGYwYTI1OWM0In19fQ=="
    signature: "JPEl2xSJglzhykvvP/CRh5idRx0uO9qlJALDeQB7c0vds9NjzB8TXZhOdeDI8gxwCqKps6MSW1oh23yx9WKXbxt2HsmXfBmQYSV6HkJ+qWa//D8/Gi8osGa3MMi90CWRlalmZTGFYaF9ALimrLtBDBMKNnrV6MPdTaQbgRdIwUjRz6q/ST+qwR/HidrRowV23P/UNJd+/zl/mn2b4q+zpNpSsRqqlavHXrYI8aM7NtiNe6cJAafE8h6ibShCGFiaXDNpLYCzRcOWQ41HyTLFkhbeWauPw+aLCBvx49yCnhxtIlpXNnA4scmNTEruKLaleTYuj4PKqwqr6l/25NZgV08lcgfM3GpXgK4JQD/o3VYYAZvFjTBgrM0VBbKQCn+akLECi9bozRFWM9JPF6xrvYKLK0IlCX3bYCtdUtzHf2wfvVEoIp1XGdzYMPZUvRLUT22TO76bFyXPEOplNEEIhuQa1OpvXukLNmiibqLNsBD9fIdaMPRLw/A4SSC+yrU8LgGYCN4dco01vpapRBmqcjeVfP1YPaA+zUMscBHLgFlwCWSYsNMmwP89nAJOyM+UXFYNsZ5y7bEMwXimneFhEPxDqoIeHwtrbS3Gkiw40NdPDcQhTXMkvdlCKsoC7IbHsj2vTsZxTLKH5os29NjBeUS4/2DqpyfCCgfImXFhrEo="

# Premium login configuration
login:
  disabled: false
  use-premium-uuid: true
  strict-names: false

afk:
  disabled: false
  seconds: 120
  player-list-name: "<player-name>"
  player-list-name-afk: "<player-name> <yellow>AFK</yellow>"
  messages.enabled: false

discord:
  disabled: false
  token: ""
  server-avatar-url: "https://minions.ddns.net/minecraft/server-icon.png"
  avatar-url: "https://mineskin.eu/helm/<player-name>.png"
  guild:
    id: 672642223942139915
    channel: 985847790594834452
    webhook: "Yawa"
  format:
    message: "[<aqua><player-name></aqua>] <aqua>»</aqua> "

chat:
  disabled: false
  format:
    message: "[<player-name>] <gold>»</gold> "
    message-to: "[<light_purple><player-name></light_purple>] <light_purple>«</light_purple> "
    message-from: "[<light_purple><player-name></light_purple>] <light_purple>»</light_purple> "

notify:
  disabled: false
  debounce: 10
  item:
    - DIAMOND
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DIAMOND_BLOCK
    - DIAMOND_SWORD
    - DIAMOND_SHOVEL
    - DIAMOND_PICKAXE
    - DIAMOND_AXE
    - DIAMOND_HOE
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - DIAMOND_HORSE_ARMOR
    - ANCIENT_DEBRIS
    - NETHERITE_INGOT
    - NETHERITE_SCRAP
    - NETHERITE_SWORD
    - NETHERITE_SHOVEL
    - NETHERITE_PICKAXE
    - NETHERITE_AXE
    - NETHERITE_HOE
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - ENCHANTED_GOLDEN_APPLE
    - ELYTRA
    - EMERALD
    - EMERALD_BLOCK