# Yawa - general all-in-one plugin for any of my personally deployed minecraft servers.
#
# https://github.com/gavenda/yawa
#
# The main reason this plugin was created so I can instantly get server up to date with any Spigot updates or fix
# any errors I found and also remove unnecessary features I don't really want.
#
# This is simply micro optimizing, and yes, I'm doing it for evil.

# Database configuration
db:
  # You can use any jdbc url as long as you can somehow provide the driver on the classpath
  # By default it is set to use SQLite
  # Use this for MySQL connections: <jdbc:mysql://localhost:3306/db>
  jdbc-url: "jdbc:sqlite:plugins/Yawa/yawa.db"
  username: root
  password: ''

# Permission feature configuration
permission:
  disabled: true

# Essentials feature configuration
essentials:
  disabled: true

# Ping feature configuration
ping:
  disabled: false

# Image feature configuration
image:
  disabled: false

# Player head feature configuration
player-head:
  disabled: false

# Keep alive override, should not be enabled unless you actually need it
keep-alive:
  disabled: true
  timeout: 180

# Tab List feature configuration
tab-list:
  disabled: false
  header: "<gold>Yawaland</gold>"
  footer: "<server-player-count> / <server-player-max>"

# Sleep - Configure how we pass the night, defaults to desired values.
# based on Harbor (https://github.com/nkomarn/Harbor)
sleep:
  disabled: false
  time-rate: 85
  kick-seconds: 15
  messages:
    chat:
      enabled: true

# Ender dragon battle configuration
ender:
  disabled: true

# Sit feature configuration
sit:
  disabled: false

# Skin feature configuration
skin:
  disabled: false
  default-texture:
    value: "ewogICJ0aW1lc3RhbXAiIDogMTU5OTcxNzAyNzM1NCwKICAicHJvZmlsZUlkIiA6ICIwYTMyZGNkNDkxMjI0Zjc0OTdmYmM3MzJkOGVlZTJkYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJCYXNpY0hlbnJ5XyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xNjNmNzBiYzcxOGIzZGIyNmMyZTI4OTVhYmUzMmIyYWFjNWQyZDczNWFiMzI0MTcxNmViZGQyM2VmZWQyNDI2IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
    signature: "I+Go6MfWxFRgVXITUN8aZQUfULZL1qM6IWoTZsZBYu3q5QXe21mUDdjCCNAJWJjDD35TVfdYD1zbenauEbPw0lqzKQV7eftxQ/A2eandKZRT/qWIjDSElo+GlTGr4nDa8g4OdM1BeknoqDTeINWKvf4izDidABFtglPNpmLVKpzIM8FrXxNDDu7Y6DSBy0239Vj6NTWxPCoOhnz816OkvuFW0+It6si5oqqTmffmZ1Cs8qmrJ6+6EcWB7W+r2/qFI2oRRvogZ28IK1g6XZkSJ3S5Ra04ZN87dnRs58Ow+sN3eJVj8FAvJAOg8HLoN4ThRRDPhrbelYFb60VYdG/AjYugMZc9/CJ3D51EqvLuJzw/Z1bqWEmSjCgIkHpD0ZK9SPxrmcP0+mYtq3mQolwtR9RuNvjvXiaMTFFza8Fnd/MO/DPAe4XbbNlRZlMINgfy/T9v83p6aM3OGVD5yNHQ/cWxHac8Fjzck/Fdj9D13PKK7hozmEoU023qWj0Z88rlUfXRl7gSNfwrGxDjlC2KQ+Jl8/siqfaau8SiQw3Z5liZAdWCab562XWzvCJwNgzfulcUK9g8Fh52pGm90KMZZloscu8ZKlGzjwe1KNE6wmf5hzhbyYmhs/pxrNZEawPCx+QuKc1MObTkNS26P6UdaDcOBlgmSZOVLmr+MqWwa3I="

# Premium login configuration
login:
  disabled: false
  use-premium-uuid: true
  strict-names: false

afk:
  disabled: false
  seconds: 120
  player-list-name: "<player-name> <yellow>AFK</yellow>"
  messages.enabled: false

chat:
  disabled: false
  format:
    message: "[<player-name>] <gold>»</gold> "
    message-to: "[<light_purple><player-name></light_purple>] <gray>«</gray> "
    message-from: "[<light_purple><player-name></light_purple>] <gray>»</gray> "
    message-discord: "[<aqua><player-name></aqua>] <gray>»</gray> "

notify:
  disabled: true
  item:
    - DIAMOND
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DIAMOND_BLOCK
    - DIAMOND_SWORD
    - DIAMOND_SHOVEL
    - DIAMOND_PICKAXE
    - DIAMOND_AXE
    - DIAMOND_HOE
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - DIAMOND_HORSE_ARMOR
    - ANCIENT_DEBRIS
    - NETHERITE_INGOT
    - NETHERITE_SCRAP
    - NETHERITE_SWORD
    - NETHERITE_SHOVEL
    - NETHERITE_PICKAXE
    - NETHERITE_AXE
    - NETHERITE_HOE
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - ENCHANTED_GOLDEN_APPLE
    - ELYTRA
    - EMERALD
    - EMERALD_BLOCK