# Yawa - general all-in-one plugin for any of my personally deployed minecraft servers.
#
# https://github.com/gavenda/yawa
#
# The main reason this plugin was created so I can instantly get server up to date with any Spigot updates or fix
# any errors I found and also remove unnecessary features I don't really want.
#
# This is simply micro optimizing, and yes, I'm doing it for evil.

# Database configuration
db:
  # You can use any jdbc url as long as you can somehow provide the driver on the classpath
  # By default it is set to use SQLite
  # Use this for MySQL connections: <jdbc:mysql://localhost:3306/db>
  jdbc-url: "jdbc:sqlite:plugins/Yawa/yawa.db"
  username: root
  password: ''

# Essentials feature configuration
essentials:
  disabled: false

# Ping feature configuration
ping:
  disabled: false

# Tab List feature configuration
tab-list:
  disabled: false
  header: "&6Yawaland"
  footer: "[server-player-count] / [server-player-max]"

# Sleep - Configure how we pass the night, defaults to desired values.
# based on Harbor (https://github.com/nkomarn/Harbor)
sleep:
  disabled: false
  messages:
    chat.enabled: true
    action-bar.enabled: true

# Ender dragon battle configuration
ender:
  disabled: false

# Sit feature configuration
sit:
  disabled: false

# Skin feature configuration
skin:
  disabled: false
  default-texture:
    value: "ewogICJ0aW1lc3RhbXAiIDogMTU5OTcxNzAyNzM1NCwKICAicHJvZmlsZUlkIiA6ICIwYTMyZGNkNDkxMjI0Zjc0OTdmYmM3MzJkOGVlZTJkYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJCYXNpY0hlbnJ5XyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xNjNmNzBiYzcxOGIzZGIyNmMyZTI4OTVhYmUzMmIyYWFjNWQyZDczNWFiMzI0MTcxNmViZGQyM2VmZWQyNDI2IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
    signature: "I+Go6MfWxFRgVXITUN8aZQUfULZL1qM6IWoTZsZBYu3q5QXe21mUDdjCCNAJWJjDD35TVfdYD1zbenauEbPw0lqzKQV7eftxQ/A2eandKZRT/qWIjDSElo+GlTGr4nDa8g4OdM1BeknoqDTeINWKvf4izDidABFtglPNpmLVKpzIM8FrXxNDDu7Y6DSBy0239Vj6NTWxPCoOhnz816OkvuFW0+It6si5oqqTmffmZ1Cs8qmrJ6+6EcWB7W+r2/qFI2oRRvogZ28IK1g6XZkSJ3S5Ra04ZN87dnRs58Ow+sN3eJVj8FAvJAOg8HLoN4ThRRDPhrbelYFb60VYdG/AjYugMZc9/CJ3D51EqvLuJzw/Z1bqWEmSjCgIkHpD0ZK9SPxrmcP0+mYtq3mQolwtR9RuNvjvXiaMTFFza8Fnd/MO/DPAe4XbbNlRZlMINgfy/T9v83p6aM3OGVD5yNHQ/cWxHac8Fjzck/Fdj9D13PKK7hozmEoU023qWj0Z88rlUfXRl7gSNfwrGxDjlC2KQ+Jl8/siqfaau8SiQw3Z5liZAdWCab562XWzvCJwNgzfulcUK9g8Fh52pGm90KMZZloscu8ZKlGzjwe1KNE6wmf5hzhbyYmhs/pxrNZEawPCx+QuKc1MObTkNS26P6UdaDcOBlgmSZOVLmr+MqWwa3I="

# Premium login configuration
login:
  disabled: true
  use-premium-uuid: false

afk:
  disabled: false
  seconds: 120
  player-list-name: "&r[player-name] &eAFK"
  messages.enabled: false

# Messages for the plugin, customize to your needs.
messages:
  # Messages with placeholder support
  afk-entry: "&e[player-name] is now AFK"
  afk-leave: "&e[player-name] is no longer AFK"
  action-bar-sleeping: "&e[world-sleeping] out of [world-player-count] players are sleeping"
  action-bar-sleeping-done: "&eEveryone is now sleeping"
  chat-sleeping:
    - "&ePassing the night"
  chat-sleeping-done:
    - "&eThe night has passed"
  player-enter-bed: "&e[player-name] is now sleeping"
  player-left-bed: "&e[player-name] got out of bed"
  player-afk-start: "&eYou are now AFK"
  player-afk-end: "&eYou are no longer AFK"
  player-sit-start: "&eYou are now sitting"
  player-sit-end: "&eYou are no longer sitting"
  skin-generate: "&eGenerating skin please wait..."
  skin-applied: "&eSkin successfully applied"
  skin-retrieve: "&eRetrieving premium player skin..."
  skin-not-found: "&cCannot find premium player with that name"
  skin-rate-limit: "&cWe have reached our rate limits for changing skins, please try again later"
  skin-reject: "&cPlease pass a valid url that starts with http or https"
  skin-reset: "&eYour skin has been reset"
  ender-battle-start: "&eA battle for the ender dragon has begun and you are forced to join..."
  ender-battle-teleport: "&eYou have been teleported by an unknown entity to fight the ender dragon"
  # Messages with no placeholder support
  feature-disabled: "&eThis feature is currently disabled"
  feature-set-disabled: "&eFeature has been disabled"
  feature-set-enabled: "&eFeature has been enabled"
  plugin-reload: "&ePlugin reloaded"
  plugin-reload-config: "&ePlugin configuration reloaded"
  login-invalid-session: "&rInvalid session."
  login-invalid-token: "&rInvalid token."
  login-invalid-request: "&rMalicious login detected."
  login-invalid-session-retry: "&rCracked client detected. Please reconnect to initiate cracked login."
  login-name-illegal: "&rName contains illegal characters."
  login-name-short: "&rName is too short (at least 3 characters)."
  login-name-long: "&rName is too long (maximum of 16 characters)."
  login-error: "&rA login error occurred."