# Yawa - general all-in-one plugin for any of my personally deployed minecraft servers.
#
# https://github.com/gavenda/yawa
#
# The main reason this plugin was created so I can instantly get server up to date with any Spigot updates or fix
# any errors I found and also remove unnecessary features I don't really want.
#
# This is simply micro optimizing, and yes, I'm doing it for evil.

# Database configuration
db:
  # You can use any jdbc url as long as you can somehow provide the driver on the classpath
  # By default it is set to use SQLite
  # Use this for MySQL connections: <jdbc:mysql://localhost:3306/db>
  jdbc-url: "jdbc:sqlite:plugins/Yawa/yawa.db"
  username: root
  password: ''

# Essentials feature configuration
essentials:
  disabled: false

# Ping feature configuration
ping:
  disabled: false

# Tab List feature configuration
tab-list:
  disabled: false
  header: "&6Yawaland"
  footer: "[server-player-count] / [server-player-max]"

# Sleep - Configure how we pass the night, defaults to desired values.
# based on Harbor (https://github.com/nkomarn/Harbor)
sleep:
  disabled: false
  messages:
    chat.enabled: true
    action-bar.enabled: true

# Skin feature configuration
skin:
  disabled: false

afk:
  disabled: false
  player-list-name: "&r[player-name] &eAFK"
  messages.enabled: false

# Messages for the plugin, customize to your needs.
messages:
  afk-entry: "&e[player-name] is now AFK"
  afk-leave: "&e[player-name] is no longer AFK"
  action-bar-sleeping: "&e[world-sleeping] out of [world-player-count] players are sleeping"
  action-bar-sleeping-done: "&eEveryone is now sleeping"
  chat-sleeping:
    - "&ePassing the night"
  chat-sleeping-done:
    - "&eThe night has passed"
  player-enter-bed: "&e[player-name] is now sleeping"
  player-left-bed: "&e[player-name] got out of bed"
  plugin-reload: "&ePlugin reloaded"
  plugin-config-reload: "&ePlugin configuration reloaded"
  feature-disabled: "&eThis feature is currently disabled"
  skin-generate: "&eGenerating skin please wait..."
  skin-applied: "&eSkin successfully applied."
  skin-retrieve: "&eRetrieving premium player skin..."
  skin-not-found: "&cCannot find premium player with that name"
  skin-rate-limit: "&cWe have reached our rate limits for changing skins, please try again later"
  skin-reject: "&cPlease pass a valid url that starts with http or https"
  skin-reset: "&eYour skin has been reset"