name: Yawa
description: All in one plugin for any of my personally hosted minecraft servers. Most of its code bases are taken from popular plugins.
author: Gavenda
website: https://gavenda.work
load: POSTWORLD
depend:
  - Kotlin
  - Exposed
  - ProtocolLib
  - YawaAPI

api-version: '1.16'
version: ${project.version}
main: work.gavenda.yawa.Plugin

commands:
  afk:
    description: Toggles being AFK. (Away from Keyboard)
    permission: yawa.afk
    usage: /afk

  skin:
    description: Changes your skin.
    permission: yawa.skin
    usage: /skin

  yawa:
    description: Plugin root command.
    permission: yawa
    usage: /yawa

permissions:
  yawa:
    default: op
  yawa.reload:
    default: op
  yawa.feature:
    default: op
  yawa.afk:
    default: true
  yawa.skin:
    default: true
  yawa.skin.reset:
    default: true
  yawa.skin.player:
    default: true
  yawa.skin.url:
    default: true
