name: Yawa
description: All in one plugin for any of my personally hosted minecraft servers. Most of its code bases are taken from popular plugins.
author: Gavenda
website: https://gavenda.work
database: true
api-version: '1.19'
version: ${project.version}
main: work.gavenda.yawa.Yawa
load: STARTUP
loadbefore:
  - Vault
softdepend:
  - Vault
depend:
  - YawaAPI
libraries:
  - org.jetbrains.exposed:exposed-core:0.38.2
  - org.jetbrains.exposed:exposed-dao:0.38.2
  - org.jetbrains.exposed:exposed-jdbc:0.38.2
  - com.zaxxer:HikariCP:5.0.1
  - net.dv8tion:JDA:5.0.0-alpha.12
  - club.minnced:discord-webhooks:0.8.0
commands:
  afk:
    description: Toggles being AFK. (Away from Keyboard)
    permission: yawa.afk
    usage: /<command>
  togglearmor:
    description: Toggle armor visibility.
    permission: yawa.hidden-armor.toggle
    usage: /<command>
  skin:
    description: Changes your skin.
    usage: /<command> <subcommands>
  permission:
    description: Change player/group permissions.
    usage: /<command> <player|group> <permission> <enabled:true|false>
  ping:
    description: Check your latency to the server.
    usage: /<command>
  yawa:
    description: Plugin root command.
    usage: /<command> <subcommands>
  whisper:
    description: Send a whisper to a player.
    usage: /<command> <player> <message>
    aliases: [ w, msg, tell ]
  reply:
    description: Reply to a whisper from a player.
    usage: /<command> <message>
    aliases: [ r ]
  chunk:
    description: Manages the current chunk.
    usage: /<command>
  sethome:
    description: Set the current location as your home.
    usage: /<command>
    aliases: [ sh ]
  home:
    description: Teleport to your home.
    usage: /<command>
    aliases: [ h ]
  spawn:
    description: Teleport to spawn.
    usage: /<command>
  back:
    description: Teleport to death location.
    usage: /<command>
    aliases: [ b ]
  setwarp:
    description: Set the current location as a warp with a name.
    usage: /<command> <location-name>
    aliases: [ setlocation, sl, setloc ]
  delwarp:
    description: Delete the warp specified with a name.
    usage: /<command> <location-name>
    aliases: [ dellocation, dl, delloc ]
  warp:
    description: Warp to specified location.
    usage: /<command>
    aliases: [ location, l, loc ]
permissions:
  yawa.*:
    description: Gives access to all plugin commands.
    children:
      yawa.reload: true
      yawa.ping: true
      yawa.feature: true
      yawa.afk: true
      yawa.permission.*: true
      yawa.hidden-armor.*: true
      yawa.skin.*: true
      yawa.essentials.*: true
  yawa.hidden-armor.*:
    description: Gives access to all hidden-armor commands.
    children:
      yawa.hidden-armor.toggle: true
  yawa.hidden-armor.toggle:
    description: Permission to toggle hidden armor.
    default: true
  yawa.ping:
    description: Permission to check your ping.
    default: true
  yawa.reload:
    description: Permission to reload the plugin.
    default: op
  yawa.feature:
    description: Permission to toggle plugin features.
    default: op
  yawa.afk:
    description: Permission to shown as away from keyboard.
    default: true
  yawa.skin.*:
    description: Gives access to all skin commands.
    children:
      yawa.skin.reset: true
      yawa.skin.player: true
      yawa.skin.url: true
  yawa.skin.reset:
    description: Permission to reset your skin.
    default: true
  yawa.skin.player:
    description: Permission to your skin from a premium player.
    default: true
  yawa.skin.url:
    description: Permission to set your skin from a texture url.
    default: true
  yawa.permission.*:
    description: Gives access to all permission commands.
    children:
      yawa.permission.player: true
      yawa.permission.group: true
  yawa.permission.player:
    description: Permission to change a user permission.
    default: op
  yawa.permission.group:
    description: Permission to change a group permission.
    default: op
  yawa.chunk.*:
    description: Gives access to all chunk commands.
    children:
      yawa.chunk.mark: true
      yawa.chunk.unmark: true
  yawa.chunk.mark:
    description: Permission to mark a chunk as always loaded.
    default: op
  yawa.chunk.unmark:
    description: Permission to unmark a chunk as always loaded.
    default: op
  yawa.essentials.*:
    description: Gives access to use convenience/essential commands.
    children:
      yawa.essentials.home.teleport: true
      yawa.essentials.home.set: true
      yawa.essentials.teleport.spawn: true
      yawa.essentials.teleport.death: true
      yawa.essentials.warp.teleport: true
      yawa.essentials.warp.set: true
      yawa.essentials.warp.delete: true
  yawa.essentials.home.teleport:
    description: Permission to teleport home.
    default: true
  yawa.essentials.home.set:
    description: Permission to set home.
    default: true
  yawa.essentials.teleport.spawn:
    description: Permission to teleport to world spawn.
    default: true
  yawa.essentials.teleport.death:
    description: Permission to teleport to death location.
    default: true
  yawa.essentials.warp.teleport:
    description: Permission to warp to specified location.
    default: true
  yawa.essentials.warp.set:
    description: Permission to set a warp location.
    default: true
  yawa.essentials.warp.delete:
    description: Permission to delete a warp location.
    default: true
