name: Yawa
description: All in one plugin for any of my personally hosted minecraft servers. Most of its code bases are taken from popular plugins.
author: Gavenda
website: https://gavenda.work
load: POSTWORLD
depend:
  - Kotlin
  - YawaAPI

api-version: '1.16'
version: ${project.version}
main: work.gavenda.yawa.Yawa

commands:
  afk:
    description: Toggles being AFK. (Away from Keyboard)
    permission: yawa.afk
    usage: /afk

  skin:
    description: Changes your skin.
    usage: /skin

  permission:
    description: Change player/group permissions.
    usage: /permission

  yawa:
    description: Plugin root command.
    permission: yawa
    usage: /yawa

permissions:
  yawa.*:
    description: Gives access to all plugin commands.
    children:
      yawa.reload: true
      yawa.feature: true
      yawa.afk: true
      yawa.skin.*: true
  yawa.reload:
    description: Permission to reload the plugin.
    default: op
  yawa.feature:
    description: Permission to toggle plugin features.
    default: op
  yawa.afk:
    description: Permission to shown as away from keyboard.
    default: true
  yawa.skin.*:
    description: Gives access to all skin commands.
    children:
      yawa.skin.reset: true
      yawa.skin.player: true
      yawa.skin.url: true
  yawa.skin.reset:
    description: Permission to reset your skin.
    default: true
  yawa.skin.player:
    description: Permission to your skin from a premium player.
    default: true
  yawa.skin.url:
    description: Permission to set your skin from a texture url.
    default: true
  yawa.permission.*:
    description: Gives access to all permission commands.
    children:
      yawa.permission.player: true
      yawa.permission.group: true
  yawa.permission.player:
    description: Permission to change a user permission.
    default: op
  yawa.permission.group:
    description: Permission to change a group permission.
    default: op
