name: Yawa
description: All in one plugin for any of my personally hosted minecraft servers. Most of its code bases are taken from popular plugins.
author: Gavenda
website: https://gavenda.work
database: true
api-version: '1.19'
version: ${project.version}
main: work.gavenda.yawa.Yawa
load: STARTUP
loadbefore:
  - Vault
depend:
  - YawaAPI
libraries:
  - org.jetbrains.exposed:exposed-core:0.38.2
  - org.jetbrains.exposed:exposed-dao:0.38.2
  - org.jetbrains.exposed:exposed-jdbc:0.38.2
  - com.zaxxer:HikariCP:5.0.1
  - net.dv8tion:JDA:5.0.0-alpha.12
  - club.minnced:discord-webhooks:0.8.0
commands:
  afk:
    description: Toggles being AFK. (Away from Keyboard)
    permission: yawa.afk
    usage: /afk
  imgup:
    description: Uploads an image for use by the CustomImages plugin.
    permission: yawa.image.upload
    usage: /imgup <url> <file-name>
  imgdel:
    description: Deletes an image in use by the CustomImages plugin.
    permission: yawa.image.delete
    usage: /imgdel <url> <file-name>
  toggle-armor:
    description: Toggle armor visibility.
    permission: yawa.hidden-armor.toggle
    usage: /toggle-armor
  skin:
    description: Changes your skin.
    usage: /skin <subcommands>
  permission:
    description: Change player/group permissions.
    usage: /permission <player|group> <permission> <enabled:true|false>
  ping:
    description: Check your latency to the server.
    usage: /ping
  yawa:
    description: Plugin root command.
    usage: /yawa <subcommands>
  whisper:
    description: Send a whisper to a player.
    usage: /whisper <player> <message>
    aliases: [ w, msg, tell ]
  reply:
    description: Reply to a whisper from a player.
    usage: /reply <message>
    aliases: [ r ]
  chunk:
    description: Manages the current chunk.
    usage: /chunk
permissions:
  yawa.*:
    description: Gives access to all plugin commands.
    children:
      yawa.reload: true
      yawa.ping: true
      yawa.feature: true
      yawa.afk: true
      yawa.image.*: true
      yawa.permission.*: true
      yawa.hidden-armor.*: true
      yawa.skin.*: true
  yawa.hidden-armor.toggle:
    description: Permission to toggle hidden armor.
    default: true
  yawa.image.upload:
    description: Permission to upload images for use by the CustomImages plugin.
    default: true
  yawa.image.delete:
    description: Permission to delete images in use by the CustomImages plugin.
    default: true
  yawa.ping:
    description: Permission to check your ping.
    default: true
  yawa.reload:
    description: Permission to reload the plugin.
    default: op
  yawa.feature:
    description: Permission to toggle plugin features.
    default: op
  yawa.afk:
    description: Permission to shown as away from keyboard.
    default: true
  yawa.skin.*:
    description: Gives access to all skin commands.
    children:
      yawa.skin.reset: true
      yawa.skin.player: true
      yawa.skin.url: true
  yawa.skin.reset:
    description: Permission to reset your skin.
    default: true
  yawa.skin.player:
    description: Permission to your skin from a premium player.
    default: true
  yawa.skin.url:
    description: Permission to set your skin from a texture url.
    default: true
  yawa.permission.*:
    description: Gives access to all permission commands.
    children:
      yawa.permission.player: true
      yawa.permission.group: true
  yawa.permission.player:
    description: Permission to change a user permission.
    default: op
  yawa.permission.group:
    description: Permission to change a group permission.
    default: op
  yawa.chunk.*:
    description: Gives access to all chunk commands.
    children:
      yawa.chunk.mark: true
      yawa.chunk.unmark: true
  yawa.chunk.mark:
    description: Permission to mark a chunk as always loaded.
    default: op
  yawa.chunk.unmark:
    description: Permission to unmark a chunk as always loaded.
    default: op
