name: Exposed
description: Simply provides Exposed to the classpath. Includes reflections and coroutines.
author: Gavenda
website: https://gavenda.work
load: STARTUP

api-version: '1.16'
version: ${project.version}
main: work.gavenda.yawa.exposed.Plugin