name: Adventure
description: Simply provides Adventure to the classpath. Any plugin that does this will also work as an alternative.
author: Gavenda
website: https://gavenda.work

api-version: '1.19'
version: ${project.version}
main: work.gavenda.adventure.Plugin