name: YawaAPI
description: The Yawa API.
author: Gavenda
website: https://gavenda.work
api-version: '1.19'
version: ${project.version}
main: work.gavenda.yawa.api.YawaAPI
load: STARTUP
depend:
  - ProtocolLib
  - NBTAPI
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1
  - org.jetbrains.kotlin:kotlin-reflect:1.7.21
  - net.kyori:adventure-api:4.12.0
  - net.kyori:adventure-text-minimessage:4.12.0
  - net.kyori:adventure-text-serializer-plain:4.12.0
  - net.kyori:adventure-text-serializer-gson:4.12.0
  - net.kyori:adventure-platform-bukkit:4.2.0
  - org.apache.logging.log4j:log4j-api:2.19.0
commands:
  placeholders:
    description: Lists all available placeholders.
    permission: yawa.api.placeholder
    usage: /placeholders
permissions:
  yawa.api.*:
    description: Gives access to all plugin commands.
    children:
      yawa.api.placeholder: true
  yawa.api.placeholder:
    default: op
