name: YawaAPI
description: The Yawa API.
author: Gavenda
website: https://gavenda.work
api-version: '1.19'
version: ${project.version}
main: work.gavenda.yawa.api.YawaAPI
load: STARTUP
depend:
  - Kotlin
  - ProtocolLib
softdepend:
  - Adventure
commands:
  placeholders:
    description: Lists all available placeholders.
    permission: yawa.api.placeholder
    usage: /placeholders
permissions:
  yawa.api.*:
    description: Gives access to all plugin commands.
    children:
      yawa.api.placeholder: true
  yawa.api.placeholder:
    default: op
